In [1]:
#install: conda install pytorch torchvision -c pytorch
from __future__ import print_function
import torch

pytorch is similar to numpy, and is different from tensorflow in that it does not need to run the whole graph in a single step like "session.run()"
#the eager mode of tensorflow can be run similarly; so another feature of tensorflow that make the two packages similar

The target audience for pytorch users:
    A replacement for NumPy to use the power of GPUs
    a deep learning research platform that provides maximum flexibility and speed

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  4.6566e-10,  1.1267e-35],
        [-8.5920e+09,  1.3689e+14,  4.5806e-41],
        [ 1.3694e+14,  4.5806e-41,  1.3694e+14],
        [ 4.5806e-41,  1.7718e+28,  4.2039e-45],
        [ 0.0000e+00,  0.0000e+00,  1.0646e+24]])


In [3]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [4]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [5]:
x.new_zeros(2,2)  #or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)

In [6]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

Operation:

In [7]:
x.add(1)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)

In [8]:
x #the values are not changed in place

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [9]:
x.add_(1)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)

In [10]:
x #in place add: "add_"

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)

In [11]:
torch.add(x,1)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], dtype=torch.float64)

In [12]:
x

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)

numpy-like slicing

In [13]:
x[1,:]

tensor([2., 2., 2.], dtype=torch.float64)

In [14]:
x[:,1]

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [15]:
x[1,2].item()

2.0

In [16]:
x[1,2]=4

In [17]:
x[1,2].item()

4.0

Convert between pytorch and numpy;The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

In [18]:
xn=x.numpy()
print(xn)

[[2. 2. 2.]
 [2. 2. 4.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [19]:
x.add_(10)
print(x)
print(xn)

tensor([[12., 12., 12.],
        [12., 12., 14.],
        [12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]], dtype=torch.float64)
[[12. 12. 12.]
 [12. 12. 14.]
 [12. 12. 12.]
 [12. 12. 12.]
 [12. 12. 12.]]


In [20]:
#Converting NumPy Array to Torch Tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [21]:
##convert between pandas dataframe and numpy arrays

In [22]:
import pandas as pd
dic1={"col1":['a','b','c'],"col2":[2,3,4],"col3":[4,6,10]}
df=pd.DataFrame(dic1)
df

col1  col2  col3
0    a     2     4
1    b     3     6
2    c     4    10

In [23]:
df2=df.iloc[:,1:]
df2

col2  col3
0     2     4
1     3     6
2     4    10

In [24]:
df2.as_matrix()

array([[ 2,  4],
       [ 3,  6],
       [ 4, 10]])

In [25]:
df.as_matrix()

array([['a', 2, 4],
       ['b', 3, 6],
       ['c', 4, 10]], dtype=object)

In [26]:
array1=df2.as_matrix()

In [27]:
pd.DataFrame(array1)

0   1
0  2   4
1  3   6
2  4  10

In [28]:
torch.from_numpy(array1)

tensor([[ 2,  4],
        [ 3,  6],
        [ 4, 10]])

In [29]:
x

tensor([[12., 12., 12.],
        [12., 12., 14.],
        [12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]], dtype=torch.float64)

In [30]:
x.shape

torch.Size([5, 3])

In [33]:
x[1,2]

tensor(14., dtype=torch.float64)

In [34]:
x[1,2]==13

tensor(0, dtype=torch.uint8)