## data requirement for scikit learn package

In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
data=iris.data

In [3]:
data.shape

(150, 4)

Now, look at the digits data, which are also in the right shape

In [4]:
digits = datasets.load_digits()

In [5]:
digit_data=digits.data

In [7]:
digit_data.shape

(1797, 64)

## Fitting data using the estimator API 

In [8]:
#use the svm classfier
from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100.)

In [11]:
len(digits.target)

1797

In [12]:
clf.fit(digits.data,digits.target)

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [13]:
clf.predict(digits.data[-1:])  #digits.data[-1:], the last row of the digits data

array([8])

In [27]:
clf.predict(digits.data[0:1,:])

array([0])

In [14]:
digits.data[-1:].shape

(1, 64)

In [16]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [17]:
import numpy as np

In [18]:
a=np.array([1,2,3])

In [19]:
a.shape

(3,)

In [21]:
digits.data[:,-1].shape #the last column

(1797,)

In [22]:
digits.data[-1:].shape  #the last row

(1, 64)

In [32]:
import matplotlib.pyplot as plt

In [33]:
%matplotlib inline

In [36]:
#plt.imshow(digits.data[0:1,:].reshape(8,8)) #this code works and it looks like a "0"

## model persistence

save the model to disk and then re-load it

In [38]:
import pickle

In [39]:
!pwd

/Users/hbi16859/Desktop/python_scripts


In [45]:
clf_model_handle=open("digits_svm_classifier_sklearn_20180516.model","wb")
pickle.dump(clf,clf_model_handle)
clf_model_handle.close()

In [46]:
!ls *model

digits_svm_classifier_sklearn_20180516.model


In [47]:
clf2=pickle.load(open("digits_svm_classifier_sklearn_20180516.model",'r'))

In [49]:
clf2.predict(digits.data[100:104,:])  #predict the labels for 4 rows

array([4, 0, 5, 3])