In [4]:
import pandas as pd
import numpy as np
from sklearn import svm
df = pd.DataFrame(np.random.randn(6,4),columns=list('ABCD'))
df

A         B         C         D
0 -0.193935 -2.368867  1.090054 -0.605670
1  0.351801 -1.026102  0.615629  0.382885
2 -0.689899 -0.038774 -2.642420 -0.145612
3  0.023445  1.296055  0.594652 -0.330370
4 -1.981178  1.551999 -0.007045 -1.036294
5  0.272071  2.004182  0.173589 -0.352910

In [6]:
df['E']=['a','b','c','a','b','a']

In [7]:
df['F']=[1,1,1,2,2,1]

In [8]:
clf = svm.SVC(gamma=0.001, C=100.)

In [11]:
clf.fit(df.iloc[:,0:5],df.iloc[:,5])  #the categorical data in column E is not going to work

ValueError: could not convert string to float: 'a'

In [12]:
import copy

In [13]:
df2=copy.deepcopy(df)

In [15]:
dic1={'a':1,'b':2,'c':3}
df2['E']=df2["E"].apply(lambda x: dic1[x])
df2

A         B         C         D  E  F
0 -0.193935 -2.368867  1.090054 -0.605670  1  1
1  0.351801 -1.026102  0.615629  0.382885  2  1
2 -0.689899 -0.038774 -2.642420 -0.145612  3  1
3  0.023445  1.296055  0.594652 -0.330370  1  2
4 -1.981178  1.551999 -0.007045 -1.036294  2  2
5  0.272071  2.004182  0.173589 -0.352910  1  1

In [16]:
clf.fit(df2.iloc[:,0:5],df2.iloc[:,5])  #the categorical data in column E is not going to work  #now it works

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [18]:
from numpy import array

In [19]:
b=[-2,-2,1,-0.5,1]
a=array(b)


In [20]:
b

[-2, -2, 1, -0.5, 1]

In [21]:
a

array([-2. , -2. ,  1. , -0.5,  1. ])

In [22]:
clf.predict(b) #this is not going to work

ValueError: Expected 2D array, got 1D array instead:
array=[-2.  -2.   1.  -0.5  1. ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [23]:
clf.predict(a) #this does not work

ValueError: Expected 2D array, got 1D array instead:
array=[-2.  -2.   1.  -0.5  1. ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [26]:
clf.predict(a.reshape(-1, 1))

ValueError: X.shape[1] = 1 should be equal to 5, the number of features at training time

In [30]:
df2.iloc[0:1,0:5]

A         B         C        D  E
0 -0.193935 -2.368867  1.090054 -0.60567  1

In [31]:
clf.predict(df2.iloc[0:1,0:5])  #this works

array([1])

In [32]:
clf2 = svm.SVC(gamma=0.001, C=100.)

In [ ]:
array()
clf.fit(df2.iloc[:,0:5],df2.iloc[:,5])

In [33]:
X=array(df2.iloc[:,0:5])
X

array([[-0.19393517, -2.36886717,  1.0900538 , -0.6056704 ,  1.        ],
       [ 0.35180053, -1.02610183,  0.61562868,  0.38288533,  2.        ],
       [-0.68989906, -0.03877439, -2.64242044, -0.14561183,  3.        ],
       [ 0.02344519,  1.29605505,  0.59465164, -0.33036974,  1.        ],
       [-1.98117847,  1.55199885, -0.00704497, -1.0362941 ,  2.        ],
       [ 0.27207126,  2.0041822 ,  0.17358919, -0.35291034,  1.        ]])

In [34]:
Y=array(df2.iloc[:,5])
Y

array([1, 1, 1, 2, 2, 1])

In [35]:
clf2.fit(X,Y)

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [36]:
b

[-2, -2, 1, -0.5, 1]

In [37]:
a

array([-2. , -2. ,  1. , -0.5,  1. ])

In [42]:
#clf2.predict(b) #does not work
clf2.predict([b]) #it just needs to have a 2D array

array([1])

In [41]:
clf2.predict([a])  #it just needs to have a 2D array rather than 1D

array([1])

In [43]:
clf.predict([a])  #it just needs to have a 2D array rather than 1D; trained with data.frame; still ok to use just a numeric array

array([1])

In [44]:
clf.predict([b]) #it just needs to have a 2D array rather than 1D; trained with data.frame; still ok to use just a numeric array

array([1])