In [1]:
#tensorflow book
#https://github.com/BinRoot/TensorFlow-Book/
#

In [2]:
import tensorflow as tf

In [3]:
a=tf.constant(4)

In [10]:
import numpy as np

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
b=tf.Variable(np.zeros(10))

In [14]:
print(b)

<tf.Variable 'Variable_1:0' shape=(10,) dtype=float64_ref>


In [27]:
with tf.Session() as sess:
    list1=[]
    for i in range(10):
        list1.append(i)
    ops=tf.assign(b,list1)
    result=sess.run(ops)
    print(b.eval())
    print(result)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [32]:
#this won't work, suggesting the former code code only works in a standalone session

with tf.Session() as sess:
    sess.run(b.eval())
    #print(b.eval())

FailedPreconditionError: Attempting to use uninitialized value Variable_1
	 [[Node: _retval_Variable_1_0_0 = _Retval[T=DT_DOUBLE, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable_1)]]

In [33]:
#use tensorboard to visualize some computation
raw_data = np.random.normal(10, 1, 100)

alpha = tf.constant(0.05)
curr_value = tf.placeholder(tf.float32)
prev_avg = tf.Variable(0.)

update_avg = alpha * curr_value + (1 - alpha) * prev_avg

avg_hist = tf.summary.scalar("running_average", update_avg)
value_hist = tf.summary.scalar("incoming_values", curr_value)

merged = tf.summary.merge_all()
writer = tf.summary.FileWriter("./logs")

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    for i in range(len(raw_data)):
        summary_str, curr_avg = sess.run([merged, update_avg], feed_dict={curr_value: raw_data[i]})
        sess.run(tf.assign(prev_avg, curr_avg))
        print(raw_data[i], curr_avg)
        writer.add_summary(summary_str, i)

9.489597677535658 0.47447988
8.990955035940836 0.90030366
12.636418327477799 1.4871094
8.538094093128521 1.8396587
9.486504849579017 2.222001
10.478565377081141 2.634829
10.38183209894331 3.0221791
10.294467423653975 3.3857934
9.544447199246797 3.693726
9.858163806291337 4.001948
11.28157843520689 4.365929
9.398137027712893 4.6175394
9.517541259068889 4.8625393
10.06002570203249 5.1224136
9.492642434747042 5.340925
12.549311683334563 5.7013445
10.56047118620377 5.944301
9.25924562453746 6.1100483
9.984924501087383 6.303792
9.256921941794383 6.4514484
10.32207520064446 6.6449795
9.012941731539746 6.763377
9.963195723357462 6.923368
10.113182555614921 7.0828586
9.035276063186828 7.180479
11.236099439728516 7.38326
10.835763373438041 7.555885
12.207887131020033 7.788485
8.590557247543419 7.8285885
9.370752701474071 7.905697
11.565580288489764 8.088691
9.816249272442697 8.175069
11.55227532920783 8.343929
9.603625647857296 8.406914
10.298685579314684 8.501502
8.112888785880173 8.482071
8.5

In [ ]:
#tensorboard --logdir=logs   #("logs" is the path to the logs folder)
#TensorBoard 1.7.0 at http://hbi16859-mbp133.h3b.hope:6006
#I used localhost:6006 to access the tensorboard

In [34]:
writer.close()

In [36]:
va=tf.Variable(1)
with tf.Session() as sess:
    k=0
    for i in range(10):
        k+=i
    sess.run(tf.assign(va,k))
    value=sess.run(va)
    print(value)

45


In [ ]:
va1=tf.Variable(1)
with tf.Session() as sess:
    for i in range(10):
        item=tf.constant(i)
        
    sess.run(tf.assign(va,k))
    value=sess.run(va)
    print(value)

In [38]:
#logistic regression

learning_rate = 0.01
training_epochs = 100

x1 = np.random.normal(-4, 2, 1000)
x2 = np.random.normal(4, 2, 1000)
xs = np.append(x1, x2)
ys = np.asarray([0.] * len(x1) + [1.] * len(x2))

X = tf.placeholder(tf.float32, shape=(None,), name="x")
Y = tf.placeholder(tf.float32, shape=(None,), name="y")
w = tf.Variable([0., 0.], name="parameter", trainable=True)
y_model = tf.sigmoid(w[1] * X + w[0])
cost = tf.reduce_mean(-Y * tf.log(y_model) - (1 - Y) * tf.log(1 - y_model))

train_op = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    prev_err = 0
    for epoch in range(training_epochs):
        err, _ = sess.run([cost, train_op], {X: xs, Y: ys})
        if epoch % 100 == 0:
            print(epoch, err)
        if abs(prev_err - err) < 0.0001:
            break
        prev_err = err
    w_val = sess.run(w, {X: xs, Y: ys})

0 0.6931461


In [39]:
tf.Print(w)

TypeError: Print() missing 1 required positional argument: 'data'

In [43]:
print(w)

<tf.Variable 'parameter_1:0' shape=(2,) dtype=float32_ref>


In [42]:
with tf.Session() as sess:
    print(w.eval())
    #sess.run(w)

FailedPreconditionError: Attempting to use uninitialized value parameter_1
	 [[Node: _retval_parameter_1_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](parameter_1)]]