In [1]:
import numpy as np

In [2]:
def bootstrap_res(X, n=None):
    if n == None:
        n = len(X)
        
    resample_i = np.floor(np.random.rand(n)*len(X)).astype(int)
    X_resample = X[resample_i]
    return X_resample

In [3]:
a=[[1,2,3,4],[2,3,4,5],[4,5,6,7]]
b=np.array(a)

In [4]:
bootstrap_res(b,10)

array([[2, 3, 4, 5],
       [4, 5, 6, 7],
       [4, 5, 6, 7],
       [1, 2, 3, 4],
       [4, 5, 6, 7],
       [4, 5, 6, 7],
       [4, 5, 6, 7],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [2, 3, 4, 5]])

In [7]:
c=np.random.rand(6)
c

array([0.71257901, 0.52054844, 0.16441657, 0.74534665, 0.49179052,
       0.03046022])

In [8]:
bootstrap_res(c,20)

array([0.03046022, 0.03046022, 0.16441657, 0.16441657, 0.71257901,
       0.49179052, 0.71257901, 0.03046022, 0.16441657, 0.16441657,
       0.52054844, 0.74534665, 0.52054844, 0.03046022, 0.71257901,
       0.16441657, 0.52054844, 0.74534665, 0.16441657, 0.03046022])