In [5]:
import numpy as np

In [6]:
def bootstrap_resample(X, n=None):
    """ Bootstrap resample an array_like
    Parameters
    ----------
    X : array_like
      data to resample
    n : int, optional
      length of resampled array, equal to len(X) if n==None
    Results
    -------
    returns X_resamples
    """
    if n == None:
        n = len(X)
        
    resample_i = np.floor(np.random.rand(n)*len(X)).astype(int)
    X_resample = X[resample_i]
    return X_resample

In [15]:
a=[[1,2,3,4],[2,3,4,5],[4,5,6,7]]
b=np.array(a)

In [18]:
bootstrap_resample(b,10)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [4, 5, 6, 7],
       [2, 3, 4, 5],
       [2, 3, 4, 5],
       [2, 3, 4, 5],
       [4, 5, 6, 7],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [2, 3, 4, 5]])

In [19]:
np.random.rand(6)

array([0.36720369, 0.84178806, 0.85306629, 0.51820756, 0.97541633,
       0.59503345])

In [24]:
b[[1,2,1,2,1,2,0,0]] #numpy array can be access this way; this is really useful

array([[2, 3, 4, 5],
       [4, 5, 6, 7],
       [2, 3, 4, 5],
       [4, 5, 6, 7],
       [2, 3, 4, 5],
       [4, 5, 6, 7],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])